language: node_js
env:
  - CXX=g++=4.8
node_js:
  - "8"
  - "9"
  - "10"
before_install:
  - yarn global add npm
script:
  - "yarn run test"
notifications:
  irc: "chat.freenode.net#mrnodebot"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
