language: node_js
node_js:
  - "5"
  - "6"
  - "7"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm test"
notifications:
  irc: "chat.freenode.net#mrnodebot"
