language: node_js
env:
  - CXX=g++=4.8
node_js:
  - "7"
  - "8"
  - "9"
before_install:
  - sudo apt-get -y install libicu-dev
  - npm install -g npm
script:
  - "npm run-script lint"
  - "npm test"
notifications:
  irc: "chat.freenode.net#mrnodebot"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
